commands:
  - name: http-target
    cmd: "httptool"
    args: ["serve"]
    restartTries: 0
  - name: task
    cmd: "./bin/events-bridge"
    env:
      EB_CONFIG_CONTENT: |
        source:
          type: "mqtt"
          options:
            address: "localhost:1883"
            topic: "test/topic"
            client_id: "mqtt-to-http-client"
            consumer_group: "mqtt-to-http-group"

        target:
          type: "http"
          options:
            method: "POST"
            url: "http://localhost:8080/api/data"
          routines: 8

        runners:
          - type: "wasm"
            options:
              path: "./testers/bin/wasmrunner.wasm"
            routines: 8
    args: []
    restartTries: 0
  - name: mqtt-source
    cmd: "mqtttool"
    args: ["send", "--interval", "500us", "--payload", "{counter} - {nowtime}"]
    startAfter: "2s"
killOthers: true
